### ISSUE TITLE
OnKeyUp/Down - Feature to specify the key

### ISSUE THREAD

**Issue by NeekoDev** [altv-mango/altv-mango#15]
Hi,

For the moment, we use `@OnKeyUp` / `@OnKeyDown` like this : 

```ts
@OnKeyUp()
public onKeyUpPressed(@Param('key') key: number): void {
    if (key === X) { ... }
}
```
It could be possible to update this decorator to directly specify the key? Like : 

```ts
@OnKeyUp('e')
public onEat(): void {
    ...
}
```
We can use Guard but I'm making this suggestion here after having discussed it with 5exyGuy.

**Comment by 5exyGuy** [comment]
https://github.com/altv-mango/altv-mango/blob/main/CHANGELOG.md#136---2024-03-22
